:set number
syntax on
:set autoread

" Pathogen
execute pathogen#infect()

" Syntastic
let g:syntastic_check_on_open=1
let g:syntastic_enable_highlighting=1
let g:syntastic_warning_symbol=">"
let g:syntastic_error_symbol=">>"
let g:syntastic_c_include_dirs = [ '/opt/local/include/' ]

" Customize the editor
:set tabstop=4
:set shiftwidth=4 " the tabshift
:set hlsearch
execute pathogen#infect()

" Automatic c indentation
:filetype on
:autocmd FileType c,cpp :set cindent
